# Generated by Django 5.1.6 on 2025-03-06 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orderdetails',
            fields=[
                ('orderdetailid', models.AutoField(db_column='OrderDetailID', primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(db_column='Quantity')),
                ('subtotal', models.DecimalField(db_column='Subtotal', decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'orderdetails',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('orderid', models.AutoField(db_column='OrderID', primary_key=True, serialize=False)),
                ('totalamount', models.DecimalField(db_column='TotalAmount', decimal_places=2, max_digits=10)),
                ('orderdate', models.DateTimeField(blank=True, db_column='OrderDate', null=True)),
            ],
            options={
                'db_table': 'orders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('productid', models.AutoField(db_column='ProductID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=100)),
                ('price', models.DecimalField(db_column='Price', decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField(db_column='Stock')),
            ],
            options={
                'db_table': 'products',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('transactionid', models.AutoField(db_column='TransactionID', primary_key=True, serialize=False)),
                ('paymentstatus', models.CharField(db_column='PaymentStatus', max_length=50)),
                ('paymentdate', models.DateTimeField(blank=True, db_column='PaymentDate', null=True)),
            ],
            options={
                'db_table': 'transactions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userid', models.AutoField(db_column='UserID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=100)),
                ('email', models.CharField(db_column='Email', max_length=100, unique=True)),
                ('role', models.CharField(db_column='Role', max_length=50)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
