# Generated by Django 5.1.6 on 2025-03-06 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_authgroup_authgrouppermissions_authpermission_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={},
        ),
    ]
