# Generated by Django 5.1.6 on 2025-03-07 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_users_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={},
        ),
    ]
