# Generated by Django 5.1.6 on 2025-03-19 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_users_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'managed': False},
        ),
    ]
