# Generated by Django 5.1.6 on 2025-03-20 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_users_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderdetails',
            options={},
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={},
        ),
        migrations.AlterModelOptions(
            name='transactions',
            options={},
        ),
        
    ]
