# Generated by Django 5.1.6 on 2025-03-21 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_orderdetails_options_alter_orders_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderdetails',
            options={},
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={},
        ),
        migrations.AlterModelOptions(
            name='transactions',
            options={},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={},
        ),
    ]
